### ISSUE TITLE
disable in production mode

### ISSUE THREAD

**Issue by xjamundx** [zertosh/invariant#15]
It might be great to disable this when `NODE_ENV` is `production`. 

obviously we can use something like `strip-loader` to accomplish that, but I see invariant is already having separate behavior for prod-mod, and maybe just not throwing would be nice.

thoughts?

**Comment by zertosh** [comment]
Throwing is the desired behavior though.

**Comment by cooperka** [comment]
@xjamundx invariants should never ever be false. If you want something that's disabled in production you could try [`warning`](https://github.com/BerkeleyTrue/warning) instead (also a mirror of Facebook's `warning`).
