### ISSUE TITLE
No PATENTS file !

### ISSUE THREAD

**Issue by CristinaCismas** [zertosh/invariant#25]
Hi, we'd like to use this in our project, but we need to be able to cite a Patents file. 
 
Any chance you could add a file explicitly stating it?

Thanks!

**Comment by appsforartists** [comment]
It appears that the LICENSE was added by a third-party.  I imagine that this should have Facebook's LICENSE and PATENTS files, but @zertosh will be able to address that better than any of us can.

**Comment by Daniel15** [comment]
Upstream (facebook/fbjs) removed the patents clause in https://github.com/facebook/fbjs/pull/269, so it should be safe to remove it here too.

**Comment by zertosh** [comment]
invariant@2.2.3 has the updated MIT facebook license
