### ISSUE TITLE
Question: is `process.env` possibly undefined?

### ISSUE THREAD

**Issue by aaronbeall** [zertosh/invariant#30]
This is more a question than an issue, sorry if there was a better place to ask this.

I noticed the [code that accesses `process.env.NODE_ENV`](https://github.com/zertosh/invariant/blob/master/invariant.js#L23). Isn't it possible that `process` itself could be undefined, leading to an error in `strict mode`?

**Comment by BerkeleyTrue** [comment]
In node, `process` and `process.env` are always defined.

If bundling for a different environment, it is standard practice to have the bundler inject a value for `process.env.NODE_ENV`.

For instance, if using webpack, you would use the webpack `DefinePlugin` to overwrite this lookup with a static value.

Or, like the readme says, use Envify if using Browserify as a bundler. Most bundling systems have a standard way of doing this.

The onus is on the consumer to make sure this is defined, not the package maintainer.
