### ISSUE TITLE
Remove @providesModule headers + update to use `error.type` instead of appending `Invariant Violation`.

### ISSUE THREAD

**Issue by cpojer** [zertosh/invariant#9]
This is now installed at FB in www and the @providesModule header fucks up jest. Can you please remove the header and update the implementation to match the one in fbjs?

**Comment by zertosh** [comment]
Fixed by 554a1797dd522585866a6603bca8e720c334f27f and 1dbf212b1f6a396bfade7a87866105bbd16dee02. Published as invariant@2.2.0
